name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/*'
      - 'docs-src/*'
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.6, 3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Python dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Install JavaScript dependencies
        run: cd tests/js && npm ci
      - name: Run pytest
        run: make test

  lint:
    name: Run format/linter/types
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.6, 3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Check Black formatting
        run: make format-check
      - name: Check flake8 warnings/errors
        run: make lint
      - name: Check type errors
        run: make types
